# Load required R packages
if (!require("pacman"))
  install.packages("pacman")
pacman::p_load(
  shiny,
  DT,
  stringdist,
  stringr,
  reshape2,
  plyr,
  dplyr,
  textclean,
  tm,
  xgboost,
  MlBayesOpt,
  purrr,
  shinythemes,
  rintrojs,
  shinyBS
)

# Define UI for application
shinyUI(
  navbarPage(
    "Fuzzy Wuzzy" ,
    collapsible = TRUE,
    theme = shinytheme("journal"),
    # shinythemes::themeSelector(),
    introjsUI(),
    selected = "Matching model",
    tabPanel(title = "Matching model",
             sidebarLayout(
               sidebarPanel(
                 # Application title
                 titlePanel(tags$b("Matching Model")),
                 br(),
                 # File Input for Reference Dataset
                 introBox(
                   fileInput("file2", "Import Reference Data CSV"),
                   data.step = 2,
                   data.intro = "Upload a reference dataset containing a list of words/names to match to here. Words must be a single column (with headers) on a CSV file.
                   Case and punctuation are automatically standardized in the model."
                 ),
                 
                 # File Input for Test Data
                 introBox(
                   fileInput("file3", "Import Test Data CSV"),
                   data.step = 3,
                   data.intro = "Upload a test dataset containing a list of words/names you want to match here. Words must be a single column (with headers) on a CSV file.
                   Case and punctuation are automatically standardized in the model."
                 ),
                 
                 # Add option to use default model or not
                 introBox(
                   radioButtons(
                     "modelchoose",
                     NULL ,
                     choiceNames = c("Use default model", "Upload new model"),
                     inline = TRUE,
                     choiceValues = c("default", "upload")
                   ),
                   data.step = 4,
                   data.intro = "This toggle allows you to use the default matching model or an uploaded new model.
                   New models can be generated by the 'Train Model' tab."
                   
                 ),
                 
                 # Option to upload new model
                 conditionalPanel(condition = "input.modelchoose == 'upload'",
                                  fileInput("file4", "Import new model")),
                 
                 # Add words to disregard while matching
                 introBox(
                   textInput(
                     "RMwords2",
                     "Add words to disregard while matching",
                     value = c(
                       'Grupo,Fundacion,Asociacion,Corporacion,Servicios,Ecuador,Banco,Company,Manufacturing,Services,Europe,Global,National,International,Incorporation,corporation,Company,holdings,holding,limited,Group,corp,gmbh,ltd,llc,inc,pte,pvt,plc,the,bv,nv,lp,l l c,n v,b v,l l p,p l c,SA,S.A.'
                     ),
                     width = NULL,
                     placeholder = NULL
                   ),
                   data.step = 5,
                   data.intro = "This function allows you to prevent model matching on generic words. Words typed here will not be considered by the model when matching. All words here are case-insensitive and must be separated by a comma"
                 ),
                 
                 # Add option to group matches
                 introBox(
                   checkboxInput("group", "Group Match Result"),
                   data.step = 6,
                   data.intro = "This checkbox allows you to display the top matches for every word in the test data. If this function is turned off, the model will instead display the top word matches in descending order of word similarity. This option may be toggled
                   after potential matches have been displayed."
                 ),
                 
                 # Input for number of matches to display per group
                 conditionalPanel(
                   condition = "input.group == true",
                   sliderInput(
                     "groupselect",
                     "Matches per group",
                     value = 5,
                     min = 0,
                     max = 10,
                     ticks = FALSE
                   )
                 ),
                 
                 # Input for number of matches to display per group
                 conditionalPanel(
                   condition = "input.group == false",
                   numericInput("percentile", "Display top N% values", value = 5)
                 ),
                 
                 fluidRow(
                   column(
                     4,
                     # Run Model Button
                     introBox(
                       bsButton("go", "Run Model", width = 106),
                       data.step = 7,
                       data.intro = "Click here to run the model after you have uploaded both test and reference data."
                     )
                   ),
                   column(
                     4,
                     # Download Button
                     introBox(
                       downloadButton("matched.csv", "Download"),
                       data.step = 8,
                       data.intro = "Click here to download the matched words after the model has been run."
                     ),offset = 0.2
                   ),
                   column(
                     4,
                     # Help button 1
                     introBox(
                       bsButton("help", "Help", width = 106),
                       data.step = 1,
                       data.intro = "Welcome to the Fuzzy Matching tool. This application was developed in order to assist in the approximate string matching of company names.
                       Before running, the model requires users to upload a CSV of words they want to match (test data), and a CSV containing a reference table (reference data).
                       When started, the model attempts to match uploaded words to the reference data. A table of matches based on word similarity will be displayed."
                       
                     )
                   )
                   )
                 
                   ),
               
               
               
               # Display Matched Output
               mainPanel(br(),dataTableOutput("displaytable"))
                 )),
    
    tabPanel(
      title = "Train New Model",
      sidebarPanel(
        # File Input for Train Data
        fileInput("file1", "Import Train Data"),
        
        fluidRow(column(6,
                        # Train Model Button
                        bsButton("go2", "Train Model")),
                 
                 column(
                   6,
                   
                   # Download Button
                   downloadButton("newmodel", "Download")
                 ))
      ),
      
      mainPanel(
        helpText(
          h4("Welcome to the Fuzzy Matching model trainer."),
          br(),
          "This part of the application allows you to retrain the fuzzy matching model based on your own data.",
          "In order to train the model, you must upload a dataset of company name matches.",
          br(),
          br(),
          " - This dataset must be a CSV file with 2 columns with headers.",
          br(),
          " - The second column of names must be the desired matches of the first column of names.",
          br(),
          br(),
          "(Important Note: Each company may only appear once per column).",
          br(),
          br(),
          "When done running, you may download the new model data for use in the matching model."
)))))
